### ISSUE TITLE
DIFF1005: Implement strain and stress calculations

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#356]
Implement strain calculation
1. [x] data object #338
2. [x] calculation #338
3. [x] test calculation #338
4. [x] read from project file #362 (requires ~~#338~~, ~~#361~~)
5. [x] write to project file #361 (requires ~~#338~~)
6. [x] write to CSV file #363 (requires ~~#338~~)
7. [x] get UI requirements / workflow ~~#339~~
8. [x] layout UI #364 (requires ~~#339~~)
9. [x] connect UI to calculation #365 (likely needs to be split up) (requires ~~#338~~, ~~#339~~, ~~#364~~)

Implement stress calculation
1. [x] data object, calculation, and test #427
32. [x] design grid file #728
4. [x] read from grid file #523 (requires #427, #522)
5. [x] write to grid file #522 (requires #427)
6. [x] write to CSV file #451 (requires #427)
7. [x] write UI #358 which is DIFF1320 (requires #427 for full functionality)

https://github.com/neutrons/PyRS/blob/master/docs/stress_strain.pdf
