### ISSUE TITLE
DIFF1320: Develop a single maintained and managed data visualization package for stress and strain maps

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#358]
User Story and Layout Design - #468  2D and 3D visualization of scalar fields

- [x] #502 First cut of Stress/Strain UI (only showing Strain)
- [x] #505 Fix Strain/Stress Viewer running on analysis
- [x] #539 Connect to StressField calculation
- [x] #632 Correctly get 33 strain for In-plane Stress case. Requires #587
- [x] #546 Remove "Calculate Stress/Strain" button and always calculate on input change
- [x] #547 #551 Capture and display error messages when loading and trying to plot
- [x] #541 Connect to other peak parameters (d_spacing, peak intensity, _etc_)
- [x] #735 Add Save/Load buttons for the StressField Requires #522 #523
- [x] #704 Add ability to load and apply d0 grid( vx, vy, vz vs d0)) Requires #525 #612 #664 #683 
- [x] #708 Change d0 grid to be created using Stress Facade
- [x] #576 Add 3D visualization
- [x] #631 Handle plotting case for 1D line scan
- [x] #635 Change 1D line scan to show point with error
- [x] #651 Add button to save StressField to CSV Requires #451
- [x] #709 Add option for detailed stress grid CSV Requires #451 
- [x] #630 Add peak overlay for measured points
- [x] #575 Add UI tests - Requires mantid-workbench conda package fixed
- [x] #588 #599 Add tests just for the Model, to make sure the backend doesn't break requirements for this UI
- [x] #675 Add ability to load multiple project files for one direction Requires #525

Small feature requests
- [x] #542 Change default SliceViewer interpolation to be bilinear.
- [x] Change scale (for Strain only) on colorbar to be X10-6  (microstrain) Should be fixed by #727 
- [x] #536 The x/y slice selection and slice position should be preserved when changing what is viewed
- [x] #550 Change FieldGrowthPolicy of QFormLayout
- [x] #634 Change 2D aspect ratio auto vs equal

Bugs
- [x] #543 Can't change colormap in Stress/Strain viewer (Upstream bug, needs to be fixed in Mantid)
- [x] #640 Stress/Strain Viewer 1D plot don't work on analysis
