### ISSUE TITLE
Stress calculation

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#427]
The strain is defined in [this document](https://github.com/neutrons/PyRS/blob/master/docs/stress_strain.pdf). The strain calculation should take in 3 `PeakCollection` objects (one for each orthogonal direction), Youngs modulus, and Poissons ration and return ???. 
* [x] Merging two overlapping grids #470
* [x] Scalar field #473
* [x] Export ScalarFieldSample to MDHistoWorkspace #478 
* [x]  Stacking scalar field samples #484
* [x] Interpolator method for ScalarField #485 
* [x]  DirectionExtents with a list of coordinates containing only one unique value #498
* [x] Detect if the PointList represents a regular grid #518
* [x] Interpolate surface scans #519
* [x] Integration test: interpolate ScalarFieldSample #500
* [x] Add the capability to have access to the fields of `PeakCollection` (including modifying d0) to `StrainField` #525
* [x] Recalculate strains and stresses after d_0 modification #612 (requires #525)
* [x] Add test data with single griding for StressField testing (HB2B_1320) #526
* [x] Add test data for multiple project files combining into a single StrainField #527
* [x] Add test data with multiple griding (different resolution for different regions of sample) for StressField testing #528
* [x] Interpolate linear scans #521 
* [x] Export ScalarFieldSample functionality to StrainField and StressField #553

**Comment by fanchercm** [comment]
I took a look at the strain_stress_calculator and took out most of the dead code.

**Comment by peterfpeterson** [comment]
Last issue is closed
