### ISSUE TITLE
Write out stress csv file

### ISSUE THREAD

**Issue by peterfpeterson** [neutrons/PyRS#451]
Write the stress information to a separate csv file from the peak fitting csv file.
- [x]  Define the CSV file spec
- [x]  Generate and test the desired CSV file
- [x]  Add configuration options for customize CSV files
- [x] Project files a strain field was created from #531
- [x] Store Young Modulus and Poisson Ratio in class StressField #537
- [x]  Store `peak_collection` reference to each StrainField #544
- [x] Store `StrainField` references for each direction in `StressField` #545
- [x] Connect full csv to facade (requires #661)

This requires to be finished first: ~#427~, <s>#537</s>

**Comment by jefrbunn** [comment]
We should include a header which contains some information about project files used, elastic constants:

- project file(s) used in stress/strain calculation
- Young's Modulus (E) [GPa]
- Poisson's ratio used 

Body:
- Sample Coordinates (vx,vy,vz)
**For each peak:**
- d-spacing (direction 1-n) n the number of directions
- FWHM (direction 1-n) n the number of directions
- Peak Height (direction 1-n) n the number of directions
- d0 (direction 1-n) n the number of directions, could be one value or many
- Strain (10x-6) (direction 1-n) n the number of directions, could be one value or many
- Stress (MPa) (direction 1-n) n the number of directions, could be one value or many

So for a file with 2 measured peaks and 3 directions:
(3 + 2 (3(6) ) = 39 columns

conveniently these should be all the things which will be visualized typically in the 2d/3d visualization which Ross is working on. 

Could we make this output configurable? with a pop-up window which one will select via checkbox what they want to ouput? Just a thought.

**Comment by peterfpeterson** [comment]
You will need 3 `StrainField` objects and 1 `StressField` object

For the items in the body:
* Sample coordinates - must be parallel between objects
* d-spacing, FWHM, peak height, d0, and strain - for each `StrainField`
* stress - `StressField` in all 3 directions (11, 22, 33)

**Comment by williamfgc** [comment]
Breaking it into subtasks:
- [ ]  Define the CSV file spec
- [ ]  Generate and test the desired CSV file
- [ ]  Add configuration options for customize CSV files

**Comment by williamfgc** [comment]
Final PR for issue in this release cycle #732
