### ISSUE TITLE
Prototype detector geometry calibration algorithm

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#49]
**Note**
This is the first in a series issues for developing algorithms and UI for HB2B's calibration.

**Tasks**

- [x] 1. Generate and verify detector masks files at 7 solid angles: 0, +/- 10, +/- 20 and +/- 30.
- [ ] 2. Calibration GUI (_test_)
    - [ ] loads 7 masks
    - [ ] reduce with masks
    - [ ] optionally but as **default** normalize reduced data by vanadium
    - [ ] **optionally** convert to dspacing
    - [ ] **compare** the convert to dspacing: from a virtual single pixel detector __or__ from 2D detector
- [ ] 3. Calibration algorithm prototype
    - [ ] fit peaks and present the result
    - [ ] evaluate the calibration result
    - [ ] refactor Chris' prototype (Quick..v2.py) by using PyRS-reducer
- [ ] 4. Implement an algorithm to mask detectors (ROI in fact) by solid angle.

**Calibration algorithms**
-  **GSAS**: GSASIIimage.py.ImageCalibrate: decided **not** to use.
- **Adopted**: Separate detector into N zones by solid angle, reduce data and align peaks.
