### ISSUE TITLE
Export ScalarFieldSample functionality to StrainField and StressField

### ISSUE THREAD

**Issue by jmborr** [neutrons/PyRS#553]
#### Description of the issue:
Much of the functionality of class `ScalarFieldSample` **return** a call to the constructor `ScalarFieldSample()`. This prevents use of these methods bychild classes:

- The following methods of `ScalarFieldSample` return a call to the constructor `ScalarFieldSample()`
  + `extract()`
  + `aggregate()`
  + `interpolate_sample()`
- The following functions defined in module `fields` return a call to the constructor `ScalarFieldSample()`:
  + `generateParameterField()`
  + `stack_scalar_field_sample()`

Child classes are more than scalar fields. They carry provenance (references to `PeakCollection` objects) and "metadata" (young modulus and poisson ratio).

#### Proposed

Switch to composition, and offer the public interface of `ScalarFieldSample` as part of the public interface of `StrainField` and `StressField`, if needed.

Currently:
```
class StrainField(ScalarFieldSample)
```
Proposed:
```
StrainField._field.__class__ == ScalarFieldSample
@property
def point_list:
    return StrainField._field.point_list  # same for values, errors, x, y, and z, if only if needed by client code
```
Functions of  `fields` returning a call to the constructor `ScalarFieldSample()` could follow the refactoring proposed for methods of `ScalarFieldSample`, if so required.

To-Do:
- [x] Switch from StrainField is a ScalarFieldSample to StrainField has a ScalarFieldSample #558
- [x] Switch from StressField is a ScalarFieldSample to StressField has a ScalarFieldSample #562
- [x] Fuse two strain fields measured along the same direction #564
- [x] Fuse two or more strain fields measured along the same direction #566
- [x] Stack two strain fields measured along different directions #553
- [x] Stack two or more strain fields measured along different directions
- [x] Switch back from StressField has a ScalarFieldSample to StressField is a ScalarFieldSample #572
- [x] Turn stress components in `StressField` to `ScalarFieldSamples` #574
- [x] Export StrainField and StressField to MDHistoWorkspace with no intepolation #571
- [x] Interpolate a StressField on a regular grid #570
- [x] Export StrainField and StressField to MDHistoWorkspace with linear intepolation #586

Blocks #427
