### ISSUE TITLE
PyRS Status Demo 2019 June

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#59]
**Demo must include**
1. HB2B project file
   - convert old HB2B data to new project file format
1. Re-reduction data (HZB) - #58, #60.
1. Peak fitting (Old HB2B) - #47.
1. Pole figure calculation (old HB2B + Chris's contribution)
1. Strain/stress calculation and mapping (old HB2B) 

**Tasks coming from demo**

During demo, a list of issues that are exposed including

- [x] PyQt4 and PyQt5 conflict: #63.

- [x] Fails to fit PseudoVoigt:

- [ ] HB2B project file shall be completed:

**Comment by peterfpeterson** [comment]
This is no longer relevant
