### ISSUE TITLE
Peak fitting: support both native and effective parameters

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#69]
**Fit result required**
  - Peak intensity (normalized)
  - FWHM
  - Peak position/center (2theta and d)
  - Mixing
  - Backgrounds

**Tasks**
- [x] Implement Pseudo-Voigt's effective parameter calculator (backend)
- [x] Implement Gaussian's effective parameter calculator (backend)
- [x] Test: legacy HB2B data of Pseudo-Voigt (backend)
- [x] Test: legacy HB2B data of Gaussian (backend)
- [x] Implement Voigt's effective parameter calculator (backend)
- [x] Test: legacy HB2B data of Voigt (backend)

**Comment by wdzhou** [comment]
This is done.
