### ISSUE TITLE
2019 December Release

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#71]
**Mid-October Instrument Commission Release**

The purpose for this pre-release is to support HB2B instrument commission with limited but necessary features.  There are three major features that are required by the instrument team.

1. Reduction and auto reduction
   - [x] Convert NeXus file to Hidra project file #85, #88
   - [x] Reduce raw data from Hidra project file to diffraction data and save to Hidra project file.
   - [ ] Masking #208 
   - [ ] Final check with auto reduction #95
   - [ ] Export calibrated geometry to Hidra project file #86

2. Manual reduction UI (front end + back-end)
   - [ ] Write manual reduction GUI #126
   - [ ] Test manual reduction GUI
   - [ ] Read and write wave length, mask and efficiency #93

3. Instrument geometry and wave length calibration
   - [ ] @wdzhou will work with @fanchercm #72

4. Peak fitting (back-end)
   - [x] Calculate effective peak parameters' value #89
   - [x] Export peak fitting result #87

5. Peak fitting (front-end)
   - [ ] Import user specified peak positions and names #96 
   - [ ] Export reduction and peak fitting summary #97, #202
   - [ ] Test peak fitting UI #74

**Hydra Project File (Back-end)**

- [ ] Design, including preparing documentation of, Hydra (HB2B) experiment project file #65
- [x] Read and write neutron counts
- [ ] Read and write instrument geometry calibration and wave length calibration #86 
- [x] Read and write 2theta-counts and d-spacing-counts
- [ ] Read and write peak fitting information #87
    - In progress
- [x] Read and write sample logs #88
- [x] Read and write instrument geometry parameters #93
- [ ] Read and write pole figure

**Reduction (Back-end)**

- [x] Reduce (convert to 2theta and d-spacing) testing data from Hydra project file
- [x] Export reduced data to Hydra project file

**Reduction (Front-end)**

- [x] Auto-reduction script to convert NeXus to Hidra project file #85 
- [ ] Re-reduction UI supports to import, reduce and export raw data from Hydra project file #75
    - In test
- [ ] Re-reduction UI supports visualization #75
   - In test

**Instrument Geometry and Wavelength Calibration**

- [x] Prepare X-ray data in Hydra format
- [x] Script read to calibrate geometry for X-ray data
- [ ] Export calibrated geometry to geometry file
- [x] Prepare HZB data in Hydra format
- [x] Develop a calibration algorithm to calibrate HZB geometry
- [x] **Generate a general calibration script** #72 

**Peak Fitting (Back-end)**

- [x] Refactoring for latest improvements on data structure and file format #74.
   - In progress
- [x] Calculate effective peak parameters #89.
- [ ] Improve API to export fitted peak parameters' value and error to front-end.
    - In progress
- [x] Peak fitting (including UI) supports to export peak fitting result to Hydra project file.

**Peak Fitting (Front-end)**

- [ ] Workflow test from importing Hidra project file to visualizing fitting result #74.
   - In progress
- [ ] Show both native and effective peak parameters in peak fitting window #69.
- [ ] Show fitting error in peak fitting window #70.
- [ ] Peak fitting (including UI) supports to import 2theta/d-spacing-count data from Hydra project file.
- [ ] Visualize peak fitting result in contour plot.
- [ ] Peak fitting (including UI) supports to export peak fitting result to Hydra project file.

**Texture (Back-end)**

- [ ] Refactor codes and methods for latest data structure and file format implemented PyRS.
- [ ] Solid angle calculation for all pixels
- [ ] Create detector masks dynamically according to solid angle.
- [ ] Texture analysis incorporates Chris' algorithm.
- [ ] Texture analysis imports data from Hydra project file.
- [ ] Texture analysis saves pole figures to Hydra project file.

**Texture (front-end)**

- [ ] Texture UI plots peak fitting residual in a different figure.
- [ ] Test workflow to import data/generate masks/fit peaks/pole figure calculation/export

**Strain/stress (Back-end)**

**Strain/stress (Front-end)**

**Comment by jefrbunn** [comment]
as part of the reduction, you can use Run 931 as a Vanadium Flood to normalize the data

**Comment by peterfpeterson** [comment]
This is being closed and replaced with a [project board](https://github.com/neutrons/PyRS/projects/4)
