### ISSUE TITLE
Hidra project file: geometry calibration R/W

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#86]
Implement and test geometry calibration read/write in Hidra project file.

**Tasks**
- [ ] Implementation for R/W of calibrated instrument geometry
- [ ] Implementation for R/W of wave length
   - With IS agree on format
- [ ] Implementation for R/W of calibrated wave length
   - With IS agree on format
- [ ] Generate test data
- [ ] Test writing
- [ ] Test reading
