### ISSUE TITLE
Hidra project file: read and write sample logs from NeXus

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#88]
**Tasks**

- [x] 1. Determine with IS which sample logs will be exported to Hidra project file
- [x] 2.  Determine with IS if the a sample log is time series, what to write to project file
- [x] 3.  Implement read and write
- [x] 4.  Test writing with Marie's example file
- [x] 5.  Test writing with old HB2B data
- [x] 6.  Test reading with Hidra project file converted from (5)

**Comment by fanchercm** [comment]
Define ROI for auto reduction (DAS ROI to pixelID)

**Comment by wdzhou** [comment]
Features requested have been implemented.
