### ISSUE TITLE
Peak fitting UI: specify peaks to fit

### ISSUE THREAD

**Issue by wdzhou** [neutrons/PyRS#96]
Reference: meeting note on 09/18

This issue works on the solution of UI for both single peak and multiple peaks (with slight overlap) fitting.

**How to set up the peak name and position**
User is required provide a CSV to provide the peak name and position also good for auto reduction.  It could be alike the peaks file used by VDrive/GSAS.

**Tasks**
- [ ] Specify peak file format and example
- [ ] Peak file parser
- [ ] Develop a UI to call peak fitting with given peaks' information

**Comment by wdzhou** [comment]
@wdzhou Start to work on this by fitting mutliple peaks but not overlapped! 

- API
- User interface
- Test data

**Comment by wdzhou** [comment]
@JeanBilheux is working on this in other PRs.
